
ALTER TABLE public.page_backgrounds
  ADD COLUMN IF NOT EXISTS fit TEXT NOT NULL DEFAULT 'cover',
  ADD COLUMN IF NOT EXISTS position TEXT NOT NULL DEFAULT 'center',
  ADD COLUMN IF NOT EXISTS blur INTEGER NOT NULL DEFAULT 0;
